export const PERMISSIONS = {
  Employees: {
    CREATE: ["SYSTEM_ADMIN_INITIATEUR"],
    LIST: [
      "SYSTEM_ADMIN_INITIATEUR",
      "SYSTEM_ADMIN_VALIDATEUR",
      "SYSTEM_ADMIN_VISITEUR",
    ],
    MODIFY: ["SYSTEM_ADMIN_INITIATEUR"],
    EVALUATE: ["SYSTEM_ADMIN_VALIDATEUR"],
    DELETE: ["SYSTEM_ADMIN_VALIDATEUR"],
  },
  Packages: {
    CREATE: ["SYSTEM_ADMIN_INITIATEUR"],
    LIST: [
      "SYSTEM_ADMIN_INITIATEUR",
      "SYSTEM_ADMIN_VALIDATEUR",
      "SYSTEM_ADMIN_VISITEUR",
    ],
    MODIFY: ["SYSTEM_ADMIN_INITIATEUR"],
    EVALUATE: ["SYSTEM_ADMIN_VALIDATEUR"],
  },
  Facilities: {
    CREATE: ["SYSTEM_ADMIN_INITIATEUR"],
    LIST: [
      "SYSTEM_ADMIN_INITIATEUR",
      "SYSTEM_ADMIN_VALIDATEUR",
      "SYSTEM_ADMIN_VISITEUR",
    ],
    MODIFY: ["SYSTEM_ADMIN_INITIATEUR"],
    EVALUATE: ["SYSTEM_ADMIN_VALIDATEUR"],
  },
  Memberships: {
    CREATE: ["SYSTEM_ADMIN_INITIATEUR", "PLAINTE_INITIATEUR"],
    LIST: [
      "SYSTEM_ADMIN_INITIATEUR",
      "PLAINTE_INITIATEUR",
      "PLAINTE_VALIDATEUR",
      "PLAINTE_VISITEUR",
    ],
    MODIFY: ["SYSTEM_ADMIN_INITIATEUR", "PLAINTE_INITIATEUR"],
    EVALUATE: ["SYSTEM_ADMIN_INITIATEUR", "PLAINTE_VALIDATEUR"],
    DELETE: ["SYSTEM_ADMIN_INITIATEUR", "PLAINTE_VALIDATEUR"],
  },
  Positions: {
    CREATE: ["SYSTEM_ADMIN_INITIATEUR"],
    LIST: [
      "SYSTEM_ADMIN_INITIATEUR",
      "SYSTEM_ADMIN_VALIDATEUR",
      "SYSTEM_ADMIN_VISITEUR",
    ],
    MODIFY: ["SYSTEM_ADMIN_INITIATEUR"],
    EVALUATE: ["SYSTEM_ADMIN_VALIDATEUR"],
    DELETE: ["SYSTEM_ADMIN_VALIDATEUR"],
  },
  Attendance: {
    CREATE: ["SYSTEM_ADMIN_INITIATEUR"],
    LIST: [
      "SYSTEM_ADMIN_INITIATEUR",
      "SYSTEM_ADMIN_VALIDATEUR",
      "SYSTEM_ADMIN_VISITEUR",
    ],
    MODIFY: ["SYSTEM_ADMIN_INITIATEUR"],
    EVALUATE: ["SYSTEM_ADMIN_VALIDATEUR"],
    DELETE: ["SYSTEM_ADMIN_VALIDATEUR"],
  },
  Reports: {
    CREATE: ["SYSTEM_ADMIN_INITIATEUR"],
    LIST: [
      "SYSTEM_ADMIN_INITIATEUR",
      "SYSTEM_ADMIN_VALIDATEUR",
      "SYSTEM_ADMIN_VISITEUR",
    ],
    MODIFY: ["SYSTEM_ADMIN_INITIATEUR"],
    EVALUATE: ["SYSTEM_ADMIN_VALIDATEUR"],
    DELETE: ["SYSTEM_ADMIN_VALIDATEUR"],
  },
} as const;
