export const PERMISSIONS = {
  Agents: {
    CREATE: ["SYSTEM_ADMIN_INITIATEUR"],
    LIST: [
      "SYSTEM_ADMIN_INITIATEUR",
      "SYSTEM_ADMIN_VALIDATEUR",
      "SYSTEM_ADMIN_VISITEUR",
    ],
    MODIFY: ["SYSTEM_ADMIN_INITIATEUR"],
    EVALUATE: ["SYSTEM_ADMIN_VALIDATEUR"],
    DELETE: ["SYSTEM_ADMIN_VALIDATEUR"],
  },
  Langues: {
    CREATE: ["SYSTEM_ADMIN_INITIATEUR"],
    LIST: [
      "SYSTEM_ADMIN_INITIATEUR",
      "SYSTEM_ADMIN_VALIDATEUR",
      "SYSTEM_ADMIN_VISITEUR",
    ],
    MODIFY: ["SYSTEM_ADMIN_INITIATEUR"],
    EVALUATE: ["SYSTEM_ADMIN_VALIDATEUR"],
  },
  Plaintes: {
    CREATE: ["SYSTEM_ADMIN_INITIATEUR", "PLAINTE_INITIATEUR"],
    LIST: [
      "SYSTEM_ADMIN_INITIATEUR",
      "PLAINTE_INITIATEUR",
      "PLAINTE_VALIDATEUR",
      "PLAINTE_VISITEUR",
    ],
    MODIFY: ["SYSTEM_ADMIN_INITIATEUR", "PLAINTE_INITIATEUR"],
    EVALUATE: ["SYSTEM_ADMIN_INITIATEUR", "PLAINTE_VALIDATEUR"],
    DELETE: ["SYSTEM_ADMIN_INITIATEUR", "PLAINTE_VALIDATEUR"],
  },
  Postes: {
    CREATE: ["SYSTEM_ADMIN_INITIATEUR"],
    LIST: [
      "SYSTEM_ADMIN_INITIATEUR",
      "SYSTEM_ADMIN_VALIDATEUR",
      "SYSTEM_ADMIN_VISITEUR",
    ],
    MODIFY: ["SYSTEM_ADMIN_INITIATEUR"],
    EVALUATE: ["SYSTEM_ADMIN_VALIDATEUR"],
    DELETE: ["SYSTEM_ADMIN_VALIDATEUR"],
  },
  Departments: {
    CREATE: ["SYSTEM_ADMIN_INITIATEUR"],
    LIST: [
      "SYSTEM_ADMIN_INITIATEUR",
      "SYSTEM_ADMIN_VALIDATEUR",
      "SYSTEM_ADMIN_VISITEUR",
    ],
    MODIFY: ["SYSTEM_ADMIN_INITIATEUR"],
    EVALUATE: ["SYSTEM_ADMIN_VALIDATEUR"],
    DELETE: ["SYSTEM_ADMIN_VALIDATEUR"],
  },
  Localisations: {
    CREATE: ["SYSTEM_ADMIN_INITIATEUR"],
    LIST: [
      "SYSTEM_ADMIN_INITIATEUR",
      "SYSTEM_ADMIN_VALIDATEUR",
      "SYSTEM_ADMIN_VISITEUR",
    ],
    MODIFY: ["SYSTEM_ADMIN_INITIATEUR"],
    EVALUATE: ["SYSTEM_ADMIN_VALIDATEUR"],
    DELETE: ["SYSTEM_ADMIN_VALIDATEUR"],
  },
} as const;
